module.export = function(app) {
	// body...

	app.get('/todo',function(req,res) {
		// body...
	});
	app.post('/todo',function(req,res) {
		// body...
	});
	app.delete('/todo',function(req,res) {
		// body...
	});
}